### ISSUE TITLE
IsPreviousLocation/GetPrevious Location vs Gemini Monsters

### ISSUE THREAD

**Issue by NaimSantos** [edo9300/ygopro-core#87]
This is a bug that can be found with an anime card, Tomato Paradise, but demonstrates the incorrect interaction of the functions mentioned with Gemini monsters.

If you Gemini Summon a Gigaplant that was summoned initially from hand, Tomato Paradise will trigger, which is incorrect. The functions to check the summoning location return true for LOCATION_HAND.  [This puzzle can be used to test it](https://cdn.discordapp.com/attachments/291708361752313866/638713256814575616/Teste_Tomato_Paradise.lua)

**Comment by AndreOliveiraMendes** [comment]
hum, aparent gemini summoning isn't updating the summon location, that would solve the problem as you would only need to do c:GetSummonLocation()==LOCATION_HAND

**Comment by edo9300** [comment]
fixed in https://github.com/edo9300/ygopro-core/commit/706cd3915d3f910417fc86d2e4115d0c1eddc995 and https://github.com/kevinlul/edopro-script-anime/commit/62c30a61e8da4d847d43981a8ee7d08063861581, part of the issue was also with the script using previouslocation, that correctly doesn't update when gemini summoning, instead of summonlocation
